services:
  server:
    image: moonknightmaf/pixelboard-server:latest
    ports:
      - "3001:3001"
  client:
    image: moonknightmaf/pixelboard-client:latest
    ports:
      - "8081:80"
    depends_on:
      - server
