apiVersion: v1
kind: Service
metadata:
  name: pixelboard-client-service
  namespace: pixel-canvas
spec:
  type: LoadBalancer
  selector:
    app: pixelboard-client
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
